{{- if and .Values.secretEnv (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "twake-harness.secretName" . }}
  labels:
    {{- include "twake-harness.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ toString $value | quote }}
  {{- end }}
{{- end }}
